{"name": "test_case01", "status": "failed", "statusDetails": {"message": "AssertionError: assert 8 == 4\n +  where 8 = add(3, 5)", "trace": "@pytest.mark.run(order=2)     #标记，-m加标记名称smoke.last，最后一个运行,run(num)设置执行顺序\n    def test_case01():\n        print('============ test_case01 =========')\n>       assert  add(3,5) == 4   #assert 断言语句，判断数据测试结果是否正确,成功的话返回值会显示一个点，失败会显示一个F\nE       assert 8 == 4\nE        +  where 8 = add(3, 5)\n\ntest_add.py:10: AssertionError"}, "start": 1647685262174, "stop": 1647685262174, "uuid": "ec5e9870-6145-46b0-a3e0-c3925aa7ef60", "historyId": "573501613aa7db34e8effb514815f42b", "testCaseId": "3331d06d650c281382ed5e024f2bca25", "fullName": "test_add#test_case01", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "suite", "value": "test_add"}, {"name": "host", "value": "WIN-N5AGDL06G55"}, {"name": "thread", "value": "41080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_add"}]}