{"name": "test_case07", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_scope.Testfixturqq object at 0x00000217A608FCC0>\n\n    def test_case07(self):\n        print('=========test_case07 ======')\n>       assert False\nE       assert False\n\ntest_scope.py:15: AssertionError"}, "start": 1647685262300, "stop": 1647685262300, "uuid": "6c237083-d2c7-4c9b-aafc-4e687107347d", "historyId": "4a4d0509795d610eb80d09a965095b69", "testCaseId": "7fe251b19929fb30b0e9469f175f998e", "fullName": "test_scope.Testfixturqq#test_case07", "labels": [{"name": "suite", "value": "test_scope"}, {"name": "subSuite", "value": "Testfixturqq"}, {"name": "host", "value": "WIN-N5AGDL06G55"}, {"name": "thread", "value": "41080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_scope"}]}