{"name": "test_case02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 11\n +  where 10 = add(5, 5)", "trace": "self = <test_add.TestAdd object at 0x00000217A6021550>\n\n    @pytest.mark.run(order=3)\n    def test_case02(self):\n        print('=========test_case02 ======')\n>       assert add(5,5) == 11\nE       assert 10 == 11\nE        +  where 10 = add(5, 5)\n\ntest_add.py:15: AssertionError"}, "start": 1647685262196, "stop": 1647685262196, "uuid": "e7f7e87c-09ca-40ce-b893-27a5aaa37f95", "historyId": "f08b4adde48282a4b98c29f1bf00e248", "testCaseId": "a0180dd744c8857c8cd8f52531e52a3a", "fullName": "test_add.TestAdd#test_case02", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_add"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "WIN-N5AGDL06G55"}, {"name": "thread", "value": "41080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_add"}]}