{"name": "test_login_failed[data0]", "status": "passed", "attachments": [{"name": "log", "source": "2f4c1ee6-ca01-4ae5-8ac8-1c29376a9868-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名为空', 'username': '', 'password': '654321', 'error_msg': '账号登录'}"}], "start": 1614175525162, "stop": 1614175528865, "uuid": "99cd8458-4aea-4c00-b18c-3f2a8ebad40b", "historyId": "d93c8b521d1ee7fc4eb27338522fd359", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "3064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}