{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "9f45656a-eb52-4e63-ba6a-6a35b5f05b4e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名错误', 'username': '财友', 'password': '654321', 'error_msg': '账号或密码错误'}"}], "start": 1614175528870, "stop": 1614175532578, "uuid": "6b2f4b75-9209-4b9c-b82b-4041c1d750fc", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "3064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}