{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "f0319e72-c792-4e4f-90fe-79c2eb3eadeb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-密码错误', 'username': '财友2sna6763', 'password': '123456', 'error_msg': '账号或密码错误'}"}], "start": 1614175924893, "stop": 1614175928609, "uuid": "70ede38e-e3d3-453b-8325-c3e23cba7453", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "15232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}