{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "3b71c82c-6c0f-4da9-850e-1db4c6bc7825-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-密码错误', 'username': '财友2sna6763', 'password': '123456', 'error_msg': '账号或密码错误'}"}], "start": 1614176070764, "stop": 1614176074467, "uuid": "1cd27bdb-1b7d-4d50-92b7-e9be5a989c5c", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "2540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}