{"name": "test_login_failed[data0]", "status": "passed", "attachments": [{"name": "log", "source": "68a2632f-ee9a-45b5-9c60-536742583190-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名为空', 'username': '', 'password': '654321', 'error_msg': '账号登录'}"}], "start": 1614176050524, "stop": 1614176054175, "uuid": "aa5fa293-0b9c-44bb-bec2-91faa6686170", "historyId": "d93c8b521d1ee7fc4eb27338522fd359", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "2540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}